sudo: required
language: generic
services:
  - docker
before_install:
  - sudo apt-get install -y expect
  - sudo ./create-context.expect
  - docker context ls
script:
  - echo "buid time"
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
